Repository ipfs/go-mfs, pull requests merged in 2018-12, with the labels that each got.

#12 feat(inode): add inode struct
  dir.go
  fd.go
  file.go
  inode.go
  mfs_test.go
  system.go
Labels: in progress

#30 go-ipfs-files 2.0
  .gx/lastpubver
  package.json
Labels: in progress

#27 [WIP] documentation notes
  README.md
  dir.go
  fd.go
  file.go
  ops.go
  system.go
Labels: in progress

#41 add documentation links in README
  README.md
Labels: in progress

#42 gx publish 0.1.29
  .gx/lastpubver
  package.json
Labels: in progress

#43 use RW lock for the `File`'s lock
  fd.go
  file.go
Labels: enhancement, in progress

#36 Various refactorings
  README.md
  dir.go
  fd.go
  file.go
  inode.go
  mfs_test.go
  repub.go
  root.go
Labels: in progress, needs review, technical debt

#45 remove the `fullSync` option from `updateChildEntry`
  dir.go
  fd.go
  root.go
Labels: in progress, needs review
